### ISSUE TITLE
Plugin isn't working

### ISSUE THREAD

**Issue by a-mazed** [huazhihao/kubespy#7]
Hi!
For some reason plugin isn't working at all with version v1.16.11-gke.5 but still working with v1.16.8-gke.15. Can you please check it?

$ kubectl spy mypod
loading spy pod...
Flag --generator has been deprecated, has no effect and will be removed in the future.
pod "spy-2557" deleted
Error from server (BadRequest): container "spy" in pod "spy-2557" is not available

**Comment by huazhihao** [comment]
fixed
