### ISSUE TITLE
~/.krew/bin/kubectl-spy: line 94: shuf: command not found

### ISSUE THREAD

**Issue by eguo** [huazhihao/kubespy#9]
I am getting this error:
~/.krew/bin/kubectl-spy: line 94: shuf: command not found

info:
NAME: spy
INDEX: default
URI: https://github.com/huazhihao/kubespy/releases/download/v0.3.3/kubespy.tar.gz
SHA256: fab1365ab650d662c4cfa2c90a7ec3617795343d257cb76304ee038cdd6d5804
VERSION: v0.3.3

**Comment by jakuboskera** [comment]
I am getting the same error.

KUBECTL VERSION: v1.18.8
SPY VERSION: v0.3.3

**Comment by btsuhako** [comment]
if you're running MacOS, you'll want to install the `coreutils` Homebrew package

```shell
brew install coreutils
```

**Comment by huazhihao** [comment]
fixed by replacing shuf with container short ID
